app:
  port: 8080

db:
  host: "localhost"
  port: 5432
  username: "animeMapUserAdmin"
  password: "12131415"
  databaseName: "ms-anime"

service:
  aws:
    region: "ap-southeast-1"
    accessKey: ""
    secretKey: ""
    s3Bucket: ""
  common:
    animeSeasonalYear:
      firstYear: 1990 
